services:
  postgres:
    image: postgres:16
    container_name: stockwise-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nnedimma11
      POSTGRES_DB: stockwise_db
    ports:
      - "5432:5432"
    volumes:
      - stockwise_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stockwise_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: stockwise-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_CONNECTION_STRING: "postgres://postgres:Nnedimma11@postgres:5432/stockwise_db?sslmode=disable"
      ML_API_URL: "http://fastapi:8000"  
    ports:
      - "8080:8080"
    volumes:
      - ./backend/.env:/app/.env

  fastapi:
    build: ./micro-services
    container_name: stockwise-fastapi
    ports:
      - "8000:8000"
    
volumes:
  stockwise_pgdata: